language: java
env:
  global:
   - secure: Pu8U6sq3dpp+p4oUQ4qtaIP3bXD6NidnnogIZXlgbd9SFoh4b12xM4fML4EzdF6U7BZJk3lMg8nrZ7cNvOGcTzlRyj4sOL64At1ZVvKBOboNEcpL2fPjYSrV4BlnTUym8oTvSV3ZMgjXzMJl1lZTUpG07cmTzA+F6RqOxuop9mpDju/XbqR/qudGS3d7Up4MOjahbNj5edLy4mWNUXRlCwdlcJjWuXmKZub9MG0ChO5CtzoRH2h7ZlTCfzx9CAOaqaOpdpxF99BVEnFc+ckAs5jKuw2hfisKzXXLRHxJh95VoI5KOBf/2fMvYTS7mObPQgHJUs04mzh/M56i0CwIZqby98xE7oZSxkYNapZOC3m2GloJS/8WlEcrqD2KKRd2ZtdbxQxlGv2QDaqiOfPIQMvh77B8WwJVKQjE0bGgCw07g2UmLg6qs3No7655oelvqQfkr/jtIiUI0Bz1hoKfBgg/w4GopjQS1x1txN41mVYjN7VczivDUU3ac8k9OHMfOp+tGHPjWIHj0OT5qPQdM8ZDJ/sTVqTMCMBFpsWs56uqT64P5yUeEi7TR0ahAxnPx3ewiWMIYOzvKGxbsO2vAV+9j1p2NDIBoSK7d+4j7pCVVg+yG3tSy3+XaXg7niMMEnL6vx7TAIsFtuqev2aGQbB3xJXF0OYv7/nxfeKEq/c=
   - secure: QSV+SIZCmV/7V7EHHgISz6mUAai8oXeEsvfJBpDXq+Et8WODjhEVWVpp1Ovv2kDRDOq/bxWSFvC3sEVBbNDgeF3UZn0zpKrx7vT6EHwoUCo9jOxIoKyXhe5j9jQUVHxtzHhPzlz31CUFWouW4u/N0A8JAJH9wi5ySKCbdXYTIE1sDtdtfsD0xVY9EHnYxsglDO4LRB9F/Ld94qcCtw8v0i2sJ+zjKs5mgY9QuTSmIl+pKCvEH6EgiswuAxFbEE19aoLrFB1KlWWoJmqjYPOJtNCi1Em4ZCoFWHfdCiTMbOxSeyTDUNP+fCpt99B1TJe51s8igolcUUwJNg43HhOuSiizoJtO8sCCusGF7m8ce2JWRgfQc9chLmfz2SUvJ9zR/acde5lL+xDWvpdD/v/YpPnj7AT4k4Fx6lVS1XYP5uIAzvh+mXe37zIBYILnSD2V2RMn4rGk+hzh31I2YUEn/JMKdOwUADRPtTCLwnREAfbuuwSs4MbA/OvZsSqPiM2HZi2oadKr/bUgpyDF1rHgseQhaQ+qAK5yBe7PqD0ijAxt1s8RJ7Ds9TubWdeODazPCpL0HRnQBaM/wqKPwAxv9WKreKP/q2KsEdelETRAZfsPatTp2IYLBOwRSmufAuk821clPFCwRYH0aX+HJwVXgZGvoTGhnVYmvzYKfUe0/xM=

addons:
  sauce_connect:
    username: modernmaster
    access_key:
      secure: zbkwnLfErAaWSdpuSX/2fc+t2PoMSEZe/HVXK7VyxUv/QBU0zn9gpn6Xfj/6vrBpFzWVCWWW+oolmeBzvjUTvO6U5L5ih31Dzokq1b9g+vHF5cjm82ZsZOFaPu95wjg2RKIayjgTNFkfg/Iach78MlIykIGoJzIXvcSoHQpEx2iEwpTPcl70IpFlyF9h3rCRsmef3QXganWKqLMuIWjArzZpXvGpdPHu8X5DARZw+FUZ636BtG2j+igZTzu7UWAW66tpvHatAI+zD5cuaRTH4CCGe7PX9EUSdZ9oSaNbf9XYeHpl8WjcJhcbkz2ScdEbrgXWuSpQZyNx7uBcz6TnLDu/kERgbrOyePdHBddAX1jzwuJA9BPukPgTOyCREeWHlnpA5Q299KYYvoF2HhvhgzomiOts51BMU6+k0kP05oviZ8UZX/Re8wSl+uPEsmMM/Z6BvZCGGnixLvJi/PY1qbJhESS4o176Id7NVDe6UVoP44NiK5VD245E1gZyC2ntzfnLvxQFuZLKYDdbuXchSdinxgaQi3WNt9nO/lZi3SfSpMpJlt9T7LjYDeuuL+ae1MHvso5EQRyuRDc6TmCn7GKMslsXwvsjwmg0lnauUcaUSUXJosEHFwUHTR1ppzd59dzRJCJpHhAZqzRCuZP+Bz5dS23zHmg7pvAcru3tziA=
  coverity_scan:
    project:
      name: modernmaster/katas
      description: Build submitted via Travis CI
    notification_email: diesel_baz@hotmail.com
    build_command_prepend: mvn clean
    build_command:   mvn -DskipTests=true compile
    branch_pattern: master

script:
- mvn verify

after_success:
- bash <(curl -s https://codecov.io/bash)